create table book (
    id bigint generated by default as identity,
    author varchar(255),
    created_date timestamp(6),
    is_available boolean not null,
    isbn varchar(255),
    title varchar(255),
    updated_date timestamp(6),
    primary key (id)
);

create table borrower (
    id bigint generated by default as identity,
    created_date timestamp(6),
    email varchar(255),
    name varchar(255),
    updated_date timestamp(6),
    primary key (id)
);

create table borrow_book (
    id bigint generated by default as identity,
    borrow_status varchar(255) check (borrow_status in ('RETURNED','BORROWED')),
    borrowed_date timestamp(6),
    returned_date timestamp(6),
    book_id bigint,
    borrower_id bigint,
    primary key (id)
)